baseURL = "https://blog.chughkabir.com/"
languageCode = "en-us"
title = "Kabir Chugh's Blog"
theme = "ia4_hugo_theme"

[params]
  description = "Kabir Chugh's Blog"
  author = "Kabir Chugh"

[environments]
  [environments.development]
    baseURL = "http://localhost:1313/"
  
[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 20
  [[menu.main]]
    name = "Dashboard"
    url = "/dashboard/"
    weight = 30
    params = { target = "_blank" }

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

[taxonomies]
  tag = "tags"
  category = "categories"
  portfolio_type = "portfolio_types"
